// expenses.js
module.exports = [
  "Venue Hire",
  "Venue Barricade",
  "Ticket Printing",
  "Box office Personnel",
  "Ushers",
  "Security",
  "Audio Technician",
  "Lighting Technician",
  "Stagehands",
  "Medical Staff",
  "Lights",
  "Stage",
  "Sound",
  "Backline",
  "Outdoor Posters",
  "Radio Advertising",
  "Digital Ads",
  "Artist Fee",
  "Flights",
  "Accommodation",
  "Catering",
];
